skip_commits:
  message: /updated readme.*/

os: "WMF 5"

install:
  - ps: .\developers-world\demo\Appveyor\Install.ps1

build: false

version: '0.1.{build}'

test_script:
  - ps: . .\Tests\appveyor.pester.ps1 -Test
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize

after_test:
  - ps: .\developers-world\demo\Appveyor\AfterTests.ps1

branches:
  only:
    - master

artifacts:
  - path: .\developers-world\demo\Appveyor\Output\Mofs.zip
    name: Mofs.zip

deploy:
  provider: S3
  access_key_id:
    secure: jjAg/q+OeFVBnXwDqdshl8thYbfLDRI9L9oSZ86KML4=
  secret_access_key:
    secure: x+UEfAU25wSYdIi9yPYXx05vM3RohG6CKXArzz2yHWw+q2EAkeqluJwWvxxJRU1j
  bucket: powershell-dsc-mofs
  region: eu-west-1
  artifact: Mofs.zip
