skip_commits:
  message: /updated readme.*/

os: "WMF 5"

environment:
  beertimeAPIkey:
    secure: p86949m++yPE0uq7wPCarmuOS4+udI3BgcYC/77apSrVtXgK4NMEmVpWrRbUURh1
  datadogAPIkey:
    secure: lxfm20g7y9I+CA5l/PEqgf+eNRMNb7NbrFJUTkFg4qbRSMAzoc+7Rhxo7iXHLf3Z

install:
  - ps: .\developers-world\demo\Appveyor\Install.ps1

build: false

version: '0.1.{build}'

test_script:
  - ps: . .\Tests\appveyor.pester.ps1 -Test
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize

after_test:
  - ps: .\developers-world\demo\Appveyor\AfterTests.ps1

branches:
  only:
    - master

deploy:
  provider: S3
  access_key_id:
    secure: jjAg/q+OeFVBnXwDqdshl8thYbfLDRI9L9oSZ86KML4=
  secret_access_key:
    secure: x+UEfAU25wSYdIi9yPYXx05vM3RohG6CKXArzz2yHWw+q2EAkeqluJwWvxxJRU1j
  bucket: powershell-dsc-mofs
  region: eu-west-1
  artifact: Mofs.zip
