skip_commits:
  message: /updated readme.*/

os: "WMF 5"

install:
  - ps: Install-PackageProvider Nuget -ForceBootstrap -Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module Pester -Force
  - ps: Install-Module PsScriptAnalyzer -force

build: false

version: '0.1.{build}'

test_script:
  - ps: Invoke-Pester .\developers-world\demo\Tests\linting.ps1
  - ps: . .\developers-world\demo\Tests\appveyor.pester.ps1 -Test
  - ps: . .\developers-world\demo\Tests\appveyor.pester.ps1 -Finalize

branches:
  only:
    - master
