skip_commits:
  message: /updated readme.*/

os: "WMF 5"

install:
  - ps: .\developers-world\demo\Appveyor\Install.ps1

build: false

version: '0.1.{build}'

before_test:
  - ps: .\developers-world\demo\Appveyor\BeforeTests.ps1

test_script:
  - ps: Invoke-Pester .\developers-world\demo\Tests\linting.ps1
  - ps: . .\developers-world\demo\Tests\appveyor.pester.ps1 -Test
  - ps: . .\developers-world\demo\Tests\appveyor.pester.ps1 -Finalize

after_test:
  - ps: .\developers-world\demo\Appveyor\AfterTests.ps1

branches:
  only:
    - master
